apiVersion: apps/v1
kind: Deployment
metadata:
  name: divapp-deploy
spec:
  selector:
    matchLabels:
      app: divapp-v1
  replicas: 3
  template:
    metadata:
      labels:
        app: divapp-v1
    spec:
     containers:
     - name: divapp
       image: divkasi/sampleapp-01:divapp
       ports:
       - containerPort: 8080
  name: divapp-deployment
