apiVersion: v1
kind: Service 
metadata:
  name: deployment-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: divapp-v1
  ports: 
    - name: http
      port: 8080 # Service Port
      targetPort: 8080 # Container Port